name: john_engine
description: Offline password hash identifier, entropy analyzer, and compliance auditor for Dart and Flutter.
version: 2.0.0
repository: https://github.com/AbdoFawzi777/john_engine
homepage: https://github.com/AbdoFawzi777/john_engine
issue_tracker: https://github.com/AbdoFawzi777/john_engine/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  crypto: ^3.0.3
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
